### ISSUE TITLE
error: unknown command "swns"

### ISSUE THREAD

**Issue by legolas-zeng** [mritd/swns#1]
你好，我按照文档，拉取到本地试了下，显示：

> [root@k8s-master swns]# kubectl plugin swns
error: unknown command "swns"
See 'kubectl plugin -h' for help and examples

插件目录：`/root/.kube/plugins/swns`

小白求教，谢谢了。

**Comment by mritd** [comment]
新版本插件体系已经变更，请参考  https://mritd.me/2018/11/30/kubectl-plugin-new-solution-on-kubernetes-1.12/

**Comment by legolas-zeng** [comment]
多谢大佬指教，我今天试了下用一个简单的go脚本执行:
>[root@k8s-master plugins]# kubectl fcom.go
exec format error

`fcom.go`是自己写的脚本`kubectl-fcom.go`，为什么会报这个`exec format error`的错，是需要指明用go运行嘛？

**Comment by mritd** [comment]
@legolas-zeng 你的 插件 需要是一个可以直接执行的文件，通俗的说法是 `./xxxx` 能跑；如果你用 go 写的话你要编译成可执行文件的

**Comment by legolas-zeng** [comment]
多谢大佬指点，成功了。万分感谢.......

**Comment by mritd** [comment]
其实有一些骚动作可以让你直接在 linux 下运行 `.go` 文件，你可以看看 linux 的 binfmt_misc 功能 和 https://github.com/erning/gorun 这个项目

**Comment by legolas-zeng** [comment]
主要是最近都在测试k8s集群，感觉很多命令敲起来好长，打算把几个常用的命令集成到插件里面，方便点。

**Comment by mritd** [comment]
> 主要是最近都在测试k8s集群，感觉很多命令敲起来好长，打算把几个常用的命令集成到插件里面，方便点。

其实有些获取方式的插件用 shell 配合 go template 更方便，刚刚塞上去一个 https://github.com/mritd/kubectl-plugins
